#!/bin/bash

out=$(openssl s_client -connect "$1":443 -servername "$1" -showcerts </dev/null 2>/dev/null | 
openssl x509 -noout -serial | grep ^serial= | cut -d= -f2)

look "$out" lecaa-serials.txt > /dev/null

[ $? -eq 0 ] && echo "$1" "$out" affected
